### ISSUE TITLE
new logo proposal

### ISSUE THREAD

**Issue by ihtiht** [NikitaChernykh/Internet-Junkie-Google-Extension#66]
Hi, I want to make a contribution to the Internet Junkie. I designed a new logo. Maybe you like. Please tell me if you want to change or add something. If you want to use this design I can send a Pull Request.

![junkie](https://user-images.githubusercontent.com/36369736/39470995-7efeb588-4d49-11e8-9a73-146893ad88c0.jpg)

![view](https://user-images.githubusercontent.com/36369736/39471008-8599ee4e-4d49-11e8-85cc-5d726f4fcdc8.jpg)

**Comment by NikitaChernykh** [comment]
@ihtiht thank you for your work! Logo looks very nice but unfortunately, the logo that I have right now plays a big role in this application. It makes it more alive than just a statistic tool. I appreciate your effort and was very surprised! Thanks again.
